### ISSUE TITLE
flask.scaffold module issue

### ISSUE THREAD

**Issue by kskrishna04** [morganstanley/testplan#1001]
Testplan is working fine till couple of weeks back. Since yesterday facing an issue that says below:

#16 1.691     from testplan.web_ui.server import WebUIServer
File "/build/testplan/testplan/web_ui/server.py", line 14, in <module>
  from .web_app import WebServer, TESTPLAN_UI_STATIC_DIR
File "/build/testplan/testplan/web_ui/web_app.py", line 12, in <module>
  from flask_restx import Resource, Api
File "/usr/local/lib/python3.10/site-packages/flask_restx/__init__.py", line 2, in <module>
  from .api import Api  # noqa
File "/usr/local/lib/python3.10/site-packages/flask_restx/api.py", line 20, in <module>
from flask.scaffold import _endpoint_from_view_func
ModuleNotFoundError: No module named 'flask.scaffold'

#16 [11/14] RUN python /build/testplan/examples/Assertions/Basic/test_plan_skip.py
#16 1.690 Traceback (most recent call last):
#16 1.690   File "/usr/local/lib/python3.10/site-packages/flask_restx/api.py", line 18, in <module>
#16 1.690     from flask.helpers import _endpoint_from_view_func
#16 1.690 ImportError: cannot import name '_endpoint_from_view_func' from 'flask.helpers' (/usr/local/lib/python3.10/site-packages/flask/helpers.py)
#16 1.690 
#16 1.690 During handling of the above exception, another exception occurred:
#16 1.690 
#16 1.690 Traceback (most recent call last):
#16 1.690   File "/build/testplan/examples/Assertions/Basic/test_plan_skip.py", line 6, in <module>
#16 1.690     from testplan import test_plan
#16 1.690   File "/build/testplan/testplan/__init__.py", line 9, in <module>
#16 1.690     from testplan.base import (
#16 1.690   File "/build/testplan/testplan/base.py", line 23, in <module>
#16 1.690     from testplan.runnable import TestRunner, TestRunnerConfig, TestRunnerResult
#16 1.690   File "/build/testplan/testplan/runnable/__init__.py", line 1, in <module>
#16 1.690     from testplan.runnable.base import (
#16 1.690   File "/build/testplan/testplan/runnable/base.py", line 48, in <module>
#16 1.691     from testplan.exporters import testing as test_exporters
#16 1.691   File "/build/testplan/testplan/exporters/testing/__init__.py", line 7, in <module>
#16 1.691     from .webserver import WebServerExporter
#16 1.691   File "/build/testplan/testplan/exporters/testing/webserver/__init__.py", line 1, in <module>
#16 1.691     from .base import WebServerExporter
#16 1.691   File "/build/testplan/testplan/exporters/testing/webserver/base.py", line 16, in <module>
#16 1.691     from testplan.web_ui.server import WebUIServer
#16 1.691   File "/build/testplan/testplan/web_ui/server.py", line 14, in <module>
#16 1.691     from .web_app import WebServer, TESTPLAN_UI_STATIC_DIR
#16 1.691   File "/build/testplan/testplan/web_ui/web_app.py", line 12, in <module>
#16 1.691     from flask_restx import Resource, Api
#16 1.691   File "/usr/local/lib/python3.10/site-packages/flask_restx/__init__.py", line 2, in <module>
#16 1.691     from .api import Api  # noqa
#16 1.691   File "/usr/local/lib/python3.10/site-packages/flask_restx/api.py", line 20, in <module>
#16 1.691     from flask.scaffold import _endpoint_from_view_func
#16 1.691 ModuleNotFoundError: No module named 'flask.scaffold'
#16 ERROR: executor failed running [/bin/sh -c python /build/testplan/examples/Assertions/Basic/test_plan_skip.py]: exit code: 1
------
 > [11/14] RUN python /build/testplan/examples/Assertions/Basic/test_plan_skip.py:
#16 1.691     from testplan.web_ui.server import WebUIServer
#16 1.691   File "/build/testplan/testplan/web_ui/server.py", line 14, in <module>
#16 1.691     from .web_app import WebServer, TESTPLAN_UI_STATIC_DIR
#16 1.691   File "/build/testplan/testplan/web_ui/web_app.py", line 12, in <module>
#16 1.691     from flask_restx import Resource, Api
#16 1.691   File "/usr/local/lib/python3.10/site-packages/flask_restx/__init__.py", line 2, in <module>
#16 1.691     from .api import Api  # noqa
#16 1.691   File "/usr/local/lib/python3.10/site-packages/flask_restx/api.py", line 20, in <module>
#16 1.691     from flask.scaffold import _endpoint_from_view_func
#16 1.691 ModuleNotFoundError: No module named 'flask.scaffold'

**Comment by kn-ms** [comment]
It looks like your version of Flask and flask-restx are not in sync. BY any chance hove not your venv started to use Flask 3.0.0 that released recently?

**Comment by kskrishna04** [comment]
@kn-ms 

Flask and flask-restx are not being used within my project, rather testplan/requirements-basic.txt gets them. Upon your comment what I noticed was that Flask earlier on my machine was 2.2.5 and now 3.0.0 was getting downloaded.

whereas flask-restx remains unchanged. (1.1.0)

in that case, I am curious to know if testplan build wasnt facing any such issue?

**Comment by kskrishna04** [comment]
just tried my build by replacing flask==2.2.5 and flask-restx==1.1.0

it worked. latest flask version is the issue here.

**Comment by kn-ms** [comment]
> @kn-ms
> 
> Flask and flask-restx are not being used within my project, rather testplan/requirements-basic.txt gets them. Upon your comment what I noticed was that Flask earlier on my machine was 2.2.5 and now 3.0.0 was getting downloaded.
> 
> whereas flask-restx remains unchanged. (1.1.0)
> 
> in that case, I am curious to know if testplan build wasnt facing any such issue?

these are the logs from a yesterday pr run:
```
Collecting Flask<2.3.0,>2.0.0 (from testplan==23.2.16->-r requirements.txt (line 1))
  Downloading Flask-2.2.5-py3-none-any.whl ([101](https://github.com/morganstanley/testplan/actions/runs/6414407288/job/17414817407#step:9:102) kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.8/101.8 kB 28.7 MB/s eta 0:00:00
```

Whic is very much in sync to our pyproject.toml: https://github.com/morganstanley/testplan/blob/main/pyproject.toml#L50 which pinning the Flask version between 2.0.0 and 2.3.0

How do you install testplan package into your project/venv?
