### ISSUE TITLE
Implement additional assertions for reporting

### ISSUE THREAD

**Issue by kelliott55** [morganstanley/testplan#184]
We are missing some report focused assertions. 
The assertion itself needs implementing and then support in the GUI & PDF reports too.

1) Markdown: accepts a snippet of markdown formatted text that will be rendered on the output report
2) Graph: used for plotting data sets from a test execution for vizualization in the report. NB a contender is javascript flot but lets consider alternatives
3) Attach: Attach a file, or all files in a directory to the report. 
4) Codelog: Log a code snippet in the report, with syntax highlighting appropriate for the language.

**Comment by ryan-collingham** [comment]
Currently we have result.graph and result.attach, still need to add result.markdown and result.codelog.
