### ISSUE TITLE
Better unicode support for python2

### ISSUE THREAD

**Issue by ryan-collingham** [morganstanley/testplan#214]
Many classes have a type schema that validates constructor params. Currently a lot of these validate strings against ``str``, which in python 2 means that unicode strings are not allowed. Most of the time there is not a good reason to disallow unicode strings.

In python 2 the `basestring` type can be used to check if a string is either `str` or `unicode`. For python 3, `basesting` can be used via `from past.builtins import basestring`.

**Comment by kn-ms** [comment]
No more python2 support
