### ISSUE TITLE
Xml not generated on Multitest cancel

### ISSUE THREAD

**Issue by cnx-tcsikos** [morganstanley/testplan#673]
Hi!

I've noticed that xml not generated for the ran (successful or not) tests when the Multitest is canceled.
Is this expected behaviour? _(Eg. in pytest it still generates the junit report)_

Example code:
``` python
@testsuite(strict_order=True)
class SleepSuite(object):
    @testcase
    def test_before_sleep_passed(self, env, result):
        pass

    @testcase
    def test_sleep(self, env, result):
        time.sleep(20) # should be more than test timeout

@test_plan(name="Testplan cancellation")
def main(plan):
    plan.add(
        MultiTest(
            name="TestCancel",
            suites=[SleepSuite()]
        )
    )
```
Execute:
Run with `--xml=xmlfolder` param and cancel after the first test passed.

Expected result:
The xmlfolder is populated with the `test_before_sleep_passed` ran successfully and `test_sleep` failed( or not present at all)

**Comment by raoyitao** [comment]
What do you mean by "Multitest is canceled", did you press ctrl+c to quit the process when Testplan is running?
If Testplan receives the quit signal and it will collect the test result that is already finished, the discard the others. So, if the whole multitest task is finished then you can see the test result (will be exported), but if any testcase has not been finished, then the whole Multitest task is discarded.

**Comment by cnx-tcsikos** [comment]
Yes, I meant ctrl+c ing.

> but if any testcase has not been finished, then the whole Multitest task is discarded.

I see.

In cases of massive Multitests, wouldn't it be more preferable to salvage the finished tests?
Or maybe the design is to not create false sense of completeness by reporting something that is not complete?

**Comment by raoyitao** [comment]
If there are massive Multitests, they'd better be scheduled to a pool (for example: process pool) and these tasks can run in parallel. Testplan can not schedules testcases or test suites individually, it communicates with task runner, assigning tasks and fetching result in unit of Multitest. So for now, it cannot pull the result of a single finished suite or testcase. I think that if a Multitest object is too big, it can be split if its suites are not related to each other, or enable `part` argument, which can make it executed faster.

**Comment by cnx-tcsikos** [comment]
Okay, thanks!
