### ISSUE TITLE
Unhandled exception from a testcase cause that suite to abort

### ISSUE THREAD

**Issue by akgalp** [morganstanley/testplan#749]
According to the [doc](https://testplan.readthedocs.io/en/latest/assertions.html?highlight=unhandled%20exception#execution-behavior) if an exception is thrown, it should abort only that testcase. But I see that if we throw an unhandled exception like in [using example code](https://github.com/morganstanley/testplan/blob/main/examples/Multitest/Basic/Initial%20Context/test_plan.py) 

```
@testsuite
class SimpleSuite(object):
    @testcase
    def test_initial_context_access(self, env, result):
        """
        env in the testcase has the content of the initial context plus the drivers
        """
        raise RuntimeError  #test created some unknown error and is unhandled
        result.equal(env.test_value, TEST_CONTEXT_VALUE)

    @testcase
    def test_driver_captured_data(self, env, result):
        """
        Just to validate the driver captured the data from context during it's startup
        """
        result.equal(env.context_user.value_from_context, TEST_CONTEXT_VALUE)
```
that test suite gets aborted.
Output:
```
Traceback (most recent call last):
  File "<path>\testplan\venv-testplan\lib\site-packages\testplan\testing\multitest\base.py", line 974, in _run_testcase
    testcase(resources, case_result)
  File "<path>\testplan\test_plan_ex.py", line 27, in test_initial_context_access
    raise RuntimeError
RuntimeError

      [test_initial_context_access] -> Error
    [SimpleSuite] -> Error
  [Initial Context example] -> Error
[Initial context example] -> Error
```
 Is that really the behavior? Is there a way to log exceptions and continue test suite execution?

**Comment by kn-ms** [comment]
Hi,

that is the default behavior, you can change that when you set up your Multitest. You should set `stop_on_error` to False. Hope this helps.

https://testplan.readthedocs.io/en/latest/api/testplan.testing.multitest.html?highlight=stop_on_error#testplan.testing.multitest.base.MultiTest

Thx
K

**Comment by akgalp** [comment]
Thank you.
